### PR TITLE
Adding AddU8 function and extra antrea metrics for reverse counters

### PR DESCRIPTION
**Pull request by srikartati**

### CODE REVIEW

**Review by antoninbas — COMMENTED** [review]
You need to update https://github.com/antoninbas/libipfix first to include the new fields.

Also could we include a field for sourceNodeName and destinationNodeName, just in case?

**Comment by srikartati** [comment]
> You need to update https://github.com/antoninbas/libipfix first to include the new fields.
> 
> Also could we include a field for sourceNodeName and destinationNodeName, just in case?
Yes planned to do that. golibipfix will not compile otherwise. I should have done that earlier

**Comment by srikartati** [comment]
> You need to update https://github.com/antoninbas/libipfix first to include the new fields.
> 
> Also could we include a field for sourceNodeName and destinationNodeName, just in case?

Yes planned to do that. Will add those fields.

**Review by antoninbas — APPROVED** [review]
LGTM

**Pull request merged**
